run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
