# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fantastical < Formula
  desc "CLI for Fantastical URL handler and AppleScript"
  homepage "https://github.com/vburojevic/fantastical-cli"
  version "0.1.3"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/vburojevic/fantastical-cli/releases/download/v0.1.3/fantastical_0.1.3_darwin_amd64.tar.gz"
    sha256 "b0ea00b83835709f58bd61c078a7267949d7dcf7728aa92522995c78715eaf8b"

    def install
      bin.install "fantastical"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/vburojevic/fantastical-cli/releases/download/v0.1.3/fantastical_0.1.3_darwin_arm64.tar.gz"
    sha256 "47bbca25e9495e7c76cc391f927208eea4bf8a457b0ee0ddeea33f719d85a1f3"

    def install
      bin.install "fantastical"
    end
  end

  test do
    system "#{bin}/fantastical", "--version"
  end
end
